### ISSUE TITLE
ConnectionRefusedError: [WinError 10061]

### ISSUE THREAD

**Issue by MoonMoon82** [cocktailpeanut/bakllava.pinokio#2]
Hi!

As soon as I start the server, this error messages appear:

```
Microsoft Windows [Version 10.0.22631.3593]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\user1\pinokio\api\bakllava.pinokio.git\llama.cpp\build\bin>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && Release\server.exe -m ../../models/ggml-model-q4_k.gguf --mmproj ../../models/mmproj-model-f16.gguf -ngl 1
error: unknown argument: --mmproj
usage: Release\server.exe [options]

options:
  -h, --help                show this help message and exit
  -v, --verbose             verbose output (default: disabled)
  -t N, --threads N         number of threads to use during computation (default: 16)
  -tb N, --threads-batch N  number of threads to use during batch and prompt processing (default: same as --threads)
  --threads-http N          number of threads in the http server pool to process requests (default: max(hardware concurrency - 1, --parallel N + 2))
  -c N, --ctx-size N        size of the prompt context (default: 512)
  --rope-scaling {none,linear,yarn}
                            RoPE frequency scaling method, defaults to linear unless specified by the model
  --rope-freq-base N        RoPE base frequency (default: loaded from model)
  --rope-freq-scale N       RoPE frequency scaling factor, expands context by a factor of 1/N
  --yarn-ext-factor N       YaRN: extrapolation mix factor (default: 1.0, 0.0 = full interpolation)
  --yarn-attn-factor N      YaRN: scale sqrt(t) or attention magnitude (default: 1.0)
Microsoft Windows [Version 10.0.22631.3593]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\Scripts\activate C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv && python src/video_stream.py
Starting video stream... Wait for a few seconds for the stream to the output to start generating.
Traceback (most recent call last):
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\urllib3\connection.py", line 400, in request
    self.endheaders()
  File "C:\Users\user1\pinokio\bin\miniconda\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\user1\pinokio\bin\miniconda\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "C:\Users\user1\pinokio\bin\miniconda\lib\http\client.py", line 976, in send
    self.connect()
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\urllib3\connection.py", line 238, in connect
    self.sock = self._new_conn()
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\urllib3\connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000125AB1BE7A0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\requests\adapters.py", line 589, in send
    resp = conn.urlopen(
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /completion (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000125AB1BE7A0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\src\video_stream.py", line 35, in <module>
    response = requests.post(url, headers=headers, json=data, stream=True)
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava\bakllava-venv\lib\site-packages\requests\adapters.py", line 622, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /completion (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000125AB1BE7A0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte'))

(bakllava-venv) (base) C:\Users\user1\pinokio\api\bakllava.pinokio.git\realtime-bakllava>
```

Any suggestions to fix this issue? 

Thank you in advance and kind regards!

**Comment by mikecastrodemaria** [comment]
Hi, same problem from my side. Did you solve it ? Thanks for help
